//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tier_DevExpressGUI_LinQ_EntityFramework.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        public string ID_CONTRACT { get; set; }
        public string ID_CUSTOMER { get; set; }
        public Nullable<int> ID_SIM { get; set; }
        public Nullable<System.DateTime> DATEREGISTER { get; set; }
        public Nullable<int> FARE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual SIM SIM { get; set; }
    }
}
