//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tier_DevExpressGUI_LinQ_EntityFramework.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARE
    {
        public int ID { get; set; }
        public Nullable<int> ID_SIM { get; set; }
        public Nullable<System.TimeSpan> TIME_STARTB7 { get; set; }
        public Nullable<System.TimeSpan> TIME_STARTA7 { get; set; }
        public Nullable<System.TimeSpan> TIME_STOPB23 { get; set; }
        public Nullable<System.TimeSpan> TIME_STOPA23 { get; set; }
    
        public virtual SIM SIM { get; set; }
    }
}
